# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3249ad7e0054b9538f301dcacbeb6426d1b1a3e9d4437e33b2dead2074cd5f7c6a15630606b7998ddae73427b5254747f8660f43ccb3c09083d7bf3bd079efe7

test:
  secret_key_base: 54251ad18b1682de5e8f9985af15fea47a2533707a8baa05ecce78422806175be70a398f080bf6c2ea778562d770a618c74aaf4b3cbb01fdd0846b992feca509

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
